# Generated by Django 3.2.8 on 2021-11-08 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Log',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('log_file', models.FileField(upload_to='C:\\Users\\geiss\\Desktop\\WS21-22\\SPP\\process-discovery\\media\\logs')),
                ('log_name', models.CharField(max_length=500)),
            ],
        ),
    ]
