# Generated by Django 3.2.9 on 2021-11-21 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logs', '0002_alter_log_log_file'),
    ]

    operations = [
        migrations.CreateModel(
            name='ComparisonMetrics',
            fields=[
                ('id',
                 models.BigAutoField(
                     auto_created=True,
                     primary_key=True,
                     serialize=False,
                     verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='LogMetrics',
            fields=[
                ('id',
                 models.BigAutoField(
                     auto_created=True,
                     primary_key=True,
                     serialize=False,
                     verbose_name='ID')),
            ],
        ),
    ]
