# Generated by Django 3.2.9 on 2021-12-01 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logs', '0003_comparisonmetrics_logmetrics'),
    ]

    operations = [
        migrations.CreateModel(
            name='LogFilter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
    ]
