# This is a basic workflow to help you get started with Actions

name: django-test

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.6, 3.7, 3.8]
      
    steps: 
    - uses: actions/checkout@v2
    
    - uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}

    - run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    
    - run: |
        python manage.py test logs

    - uses: actions/upload-artifact@v2
      if: success() || failure()
      with:
        name: test-results
        path: junit.xml