name: deploy-docker

on:
  push:
    branches: [ main ]
  workflow_dispatch:
  
jobs:
  login:
    runs-on: ubuntu-latest
    steps:
      -
        name: Login to ACR
        uses: docker/login-action@v1
        with:
          registry: ${{ secrets.AZURE_URL }}
          username: ${{ secrets.AZURE_USERNAME }}
          password: ${{ secrets.AZURE_PASSWORD }}

      - name: Build docker image
        env: 
          url: ${{ secrets.AZURE_URL }}
        run: | 
          docker build . --file Dockerfile --tag "${url}/cpm"
      
      - name: Upload image
        env:
          url: ${{ secrets.AZURE_URL }}
        run: docker push "${url}/cpm"
        
    
