name: Build a Docker image and Push it to ACR

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - uses: azure/docker-login@v1
        with:
          login-server: dominik.azurecr.io
          username: ${{ secrets.AZURE_USERNAME }}
          password: ${{ secrets.AZURE_PASSWORD }}

      - run: |
          docker build . -t dominik.azurecr.io/cpm:${{ github.sha }}
          docker push dominik.azurecr.io/cpm:${{ github.sha }}
