name: Build a Docker image and Push it to ACR

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - uses: azure/docker-login@v1
        with:
          login-server: dominik.azurecr.io
          username: ${{ secrets.AZURE_USERNAME }}
          password: ${{ secrets.AZURE_PASSWORD }}

      - run: |
          docker build . -t dominik.azurecr.io/cpm:${{ github.sha }}
          docker push dominik.azurecr.io/cpm:${{ github.sha }}
      - uses: Azure/k8s-create-secret@v1
        with:
            cointainer-registry-url: dominik.azurecr.io
            container-registry-username: ${{ secrets.AZURE_USERNAME }}
            container-registry-password: ${{ secrets.AZURE_PASSWORD }}
            secret-name: regcred
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: Azure/k8s-deploy@v1.4
        with:
          images: 'dominik.azurecr.io/cpm:${{ github.sha }}'
          kubectl-version: latest
          manifest: cpm.yaml
          imagepullsecrets: |
            regcred
