
name: test-reporter

on:
  workflow_run: 
    workflows: ['django-test']
    types:
      - completed

jobs:
  report:
    runs-on: ubuntu-latest
    steps:
    - uses: dorny/test-reporter@v1
      with:
        artifact: test-results
        name: Result
        path: '*.xml'
        reporter: java-junit