# This is a basic workflow to help you get started with Actions

name: test-reporter
on:
  workflow_run: 
    workflows: ['django-test']
    types:
      - completed

jobs:
  report:
    runs-on: ubuntu-latest
    steps:
    - name: Download Artifacts
      uses: actions/download-artifact@v2
      with:
        path: artifacts

    - name: Publish
      uses: EnricoMi/publish-unit-test-result-action@v1
      with:
        files: artifacts/*.xml
